### ISSUE TITLE
Attribute in _define

### ISSUE THREAD

**Issue by sidey79** [rejoe2/FHEM#2]
Attribute sind nicht unbedingt  verfügbar, wenn define aufgerufen wird:

https://github.com/rejoe2/FHEM/blob/cbb4addc602a3db6fa1ce73fc4be58455b5b76ba/59_Twilight.pm#L141-L142

Referenz:
https://wiki.fhem.de/wiki/DevelopmentModuleIntro#X_Define

**Comment by rejoe2** [comment]
Im Prinzip ein berechtigter Einwand. 
Afaik ist aber "global" immer das erste Gerät, das geladen wird bzw. in der config steht und daher - abgesehen von ggf. mutwilligen Manipulationen - auch mit seinen Attributen verfügbar sein sollte. 
(Den Rest der Module habe ich aus dem genannten Grund praktisch alle auf eine InternalTimer => Start-Routine umgestellt).
Bisher gab es auch keine Beschwerden, dass da was schief läuft...

**Comment by sidey79** [comment]
Ja, das scheint so zu sein. Darauf hätte ich mich halt nicht verlassen, da es dafür ja keinerlei Garantien gibt .

PS: Ist das Modul hier im GIT identisch mit dem auf SVN?

**Comment by rejoe2** [comment]
Na ja, Garantien gibt es keine, aber ich glaube nicht, dass Rudi das Verhalten von global bzw. der Einleseroutine aus fhem.cfg/configDB ändern wird (bzw. v.a. auch der Abspeicher-Logik dazu).
Im schlimmsten Fall hat man dann eben Frankfurter Daten, wenn man selbst unsachgemäß an der fhem.cfg rumfummelt...

M.E. kein Beinbruch.

Die aktuelle svn-Version ist jetzt unter https://github.com/rejoe2/fhem_Twilight zu finden; ist besser, das separat zu diskutieren, sonst bekommst du auch Benachrichtigungen, wenn ich was völlig anderes in meinen "allgemeinen FHEM-Speicher" schubse.
